# Stage Template for Updating Key Vault Secrets
# This template creates a stage with optional approval gates

parameters:
  - name: environmentName
    type: string
  - name: environmentDisplayName
    type: string
  - name: serviceConnection
    type: string
  - name: keyVaultName
    type: string
  - name: secretName
    type: string
  - name: jsonUpdates
    type: string
  - name: supportNestedKeys
    type: boolean
    default: true
  - name: createBackup
    type: boolean
    default: true
  - name: dryRun
    type: boolean
    default: false
  - name: dependsOn
    type: object
    default: []

stages:
  - stage: Update_${{ parameters.environmentName }}
    displayName: 'Update Secret - ${{ parameters.environmentDisplayName }}'
    dependsOn: ${{ parameters.dependsOn }}
    condition: succeeded()
    variables:
      - name: envName
        value: ${{ parameters.environmentName }}
    jobs:
      - template: ../jobs/update-secret-job.yml
        parameters:
          environmentName: ${{ parameters.environmentName }}
          environmentDisplayName: ${{ parameters.environmentDisplayName }}
          serviceConnection: ${{ parameters.serviceConnection }}
          keyVaultName: ${{ parameters.keyVaultName }}
          secretName: ${{ parameters.secretName }}
          jsonUpdates: ${{ parameters.jsonUpdates }}
          supportNestedKeys: ${{ parameters.supportNestedKeys }}
          createBackup: ${{ parameters.createBackup }}
          dryRun: ${{ parameters.dryRun }}
