# Job Template for Updating Key Vault Secrets
# This template defines the job that performs the actual secret update

parameters:
  - name: environmentName
    type: string
  - name: environmentDisplayName
    type: string
  - name: serviceConnection
    type: string
  - name: keyVaultName
    type: string
  - name: secretName
    type: string
  - name: jsonUpdates
    type: string
  - name: supportNestedKeys
    type: boolean
    default: true
  - name: createBackup
    type: boolean
    default: true
  - name: dryRun
    type: boolean
    default: false

jobs:
  - deployment: UpdateSecret_${{ parameters.environmentName }}
    displayName: 'Update Secret in ${{ parameters.environmentDisplayName }}'
    # Use Azure DevOps Environment for approval gates
    # Create environments in Azure DevOps: Project Settings > Environments
    environment: ${{ parameters.environmentName }}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: AzureCLI@2
              displayName: 'Update Key Vault Secret'
              inputs:
                azureSubscription: ${{ parameters.serviceConnection }}
                scriptType: 'pscore'
                scriptLocation: 'scriptPath'
                scriptPath: '$(Build.SourcesDirectory)/scripts/Update-KeyVaultSecret.ps1'
                arguments: >-
                  -KeyVaultName "${{ parameters.keyVaultName }}"
                  -SecretName "${{ parameters.secretName }}"
                  -JsonUpdates "${{ parameters.jsonUpdates }}"
                  -SupportNestedKeys:$${{ parameters.supportNestedKeys }}
                  -CreateBackup:$${{ parameters.createBackup }}
                  -DryRun:$${{ parameters.dryRun }}
                  -EnvironmentName "${{ parameters.environmentName }}"
              env:
                SYSTEM_ACCESSTOKEN: $(System.AccessToken)

            - task: PowerShell@2
              displayName: 'Generate Summary Report'
              inputs:
                targetType: 'inline'
                script: |
                  Write-Host "##[section]Update Summary"
                  Write-Host "======================================"
                  Write-Host "Environment: ${{ parameters.environmentDisplayName }}"
                  Write-Host "Key Vault: ${{ parameters.keyVaultName }}"
                  Write-Host "Secret: ${{ parameters.secretName }}"
                  Write-Host "Dry Run: ${{ parameters.dryRun }}"
                  Write-Host "Backup Created: ${{ parameters.createBackup }}"
                  Write-Host "======================================"
                pwsh: true
              condition: always()
